version: '3.1'

services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
    volumes:
      - postgres:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

volumes:
  postgres:
